# Generated by Django 5.0.6 on 2026-05-07 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("symposium", "0002_dynamic_symposium"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symposiumsession",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="symposiumsession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="symposiumsession",
            name="zeitgeist_mode",
            field=models.CharField(
                choices=[("classical", "Klasik"), ("modern", "Modern")],
                default="classical",
                max_length=20,
                verbose_name="zeitgeist modu",
            ),
        ),
        migrations.AlterField(
            model_name="symposiumturn",
            name="content",
            field=models.TextField(verbose_name="içerik"),
        ),
        migrations.AlterField(
            model_name="symposiumturn",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="symposiumturn",
            name="rag_chunks_used",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="symposiumturn",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turns",
                to="symposium.symposiumsession",
                verbose_name="oturum",
            ),
        ),
    ]
