# Generated by Django 5.0.6 on 2026-05-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="deepseek_api_key",
            field=models.CharField(
                blank=True,
                help_text="Kendi DeepSeek API anahtarınız. https://platform.deepseek.com/api_keys adresinden alabilirsiniz.",
                max_length=200,
                verbose_name="DeepSeek API anahtarı",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="Giriş için kullanılan benzersiz e-posta adresi.",
                max_length=254,
                unique=True,
                verbose_name="e-posta adresi",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Bu seçeneğin işareti kaldırıldığında hesap devre dışı kalır.",
                verbose_name="aktif",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Bu kullanıcının admin paneline erişip erişemeyeceğini belirler.",
                verbose_name="personel",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="zeitgeist_mode",
            field=models.CharField(
                choices=[
                    ("classical", "Klasik — Dönemine sadık"),
                    ("modern", "Modern — Çağdaş yorumla"),
                ],
                default="classical",
                help_text="Klasik: Filozoflar yalnızca kendi dönemlerinin bilgisiyle yanıt verir. Modern: Çağdaş yorumlar ve güncel örnekler içerebilir.",
                max_length=20,
                verbose_name="zeitgeist modu",
            ),
        ),
    ]
