# Generated by Django 5.0.6 on 2026-05-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationsession",
            name="mode",
            field=models.CharField(
                choices=[
                    ("normal", "Normal — Standart diyalog"),
                    ("socratic", "Sokratik — Sorgulama modu"),
                ],
                default="normal",
                help_text="Sokratik mod yalnızca Sokrates ve Platon için aktif edilmeli.",
                max_length=20,
                verbose_name="konuşma modu",
            ),
        ),
        migrations.AlterField(
            model_name="conversationsession",
            name="context_summary",
            field=models.TextField(
                blank=True,
                help_text="Uzun sohbetlerde eski mesajlar bu alana özetlenir. Doküman Bölüm 5.2: Son N mesaj + özet → LLM bağlam penceresi.",
                verbose_name="bağlam özeti",
            ),
        ),
        migrations.AlterField(
            model_name="conversationsession",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="İlk mesajdan otomatik türetilir. Boş bırakılırsa 'Filozof ile Sohbet — Tarih' formatı kullanılır.",
                max_length=200,
                verbose_name="sohbet başlığı",
            ),
        ),
        migrations.AlterField(
            model_name="conversationsession",
            name="zeitgeist_mode",
            field=models.CharField(
                choices=[
                    ("classical", "Klasik — Dönemine sadık"),
                    ("modern", "Modern — Çağdaş yorumla"),
                ],
                default="classical",
                help_text="Oturum oluşturulurken kullanıcının tercihinden kopyalanır. Oturum bazında değiştirilebilir.",
                max_length=20,
                verbose_name="zeitgeist modu",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(
                help_text="Kullanıcı sorusu veya filozofun yanıtı.",
                verbose_name="içerik",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="rag_chunks_used",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Bu yanıt üretilirken ChromaDB'den çekilen chunk metinleri. Şeffaflık ve debug için saklanır.",
                verbose_name="kullanılan RAG chunk'ları",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="token_count",
            field=models.IntegerField(
                default=0,
                help_text="Gemini API'nin döndürdüğü yaklaşık token sayısı.",
                verbose_name="token sayısı",
            ),
        ),
    ]
