# Generated by Django 5.0.6 on 2026-05-06 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("philosophers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="philosopher",
            name="avatar_image",
            field=models.ImageField(
                blank=True,
                help_text="Filozofun portre görseli (tercihen kare format).",
                null=True,
                upload_to="philosophers/avatars/",
                verbose_name="avatar görseli",
            ),
        ),
        migrations.AlterField(
            model_name="philosopher",
            name="core_concepts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Filozofun öne çıkan kavramları. JSON dizisi olarak girin: ["Kategorik Buyrucu", "A Priori", "Fenomen"]',
                verbose_name="temel kavramlar",
            ),
        ),
        migrations.AlterField(
            model_name="philosopher",
            name="display_order",
            field=models.IntegerField(
                default=0,
                help_text="Küçük sayı önce listelenir.",
                verbose_name="sıralama önceliği",
            ),
        ),
        migrations.AlterField(
            model_name="philosopher",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Pasif filozoflar kullanıcılara gösterilmez.",
                verbose_name="aktif",
            ),
        ),
        migrations.AlterField(
            model_name="philosopher",
            name="long_bio",
            field=models.TextField(
                blank=True,
                help_text="Profil sayfasında gösterilen kapsamlı biyografi.",
                verbose_name="detaylı biyografi",
            ),
        ),
        migrations.AlterField(
            model_name="philosopher",
            name="school",
            field=models.CharField(
                blank=True,
                help_text="Ait olduğu felsefi akım (ör: 'Alman İdealizmi')",
                max_length=100,
                verbose_name="felsefi okul",
            ),
        ),
        migrations.AlterField(
            model_name="philosopher",
            name="short_bio",
            field=models.TextField(
                help_text="Profil kartında gösterilen kısa tanıtım metni.",
                verbose_name="kısa biyografi",
            ),
        ),
        migrations.AlterField(
            model_name="philosopher",
            name="signature_style",
            field=models.TextField(
                blank=True,
                help_text="Filozofun dil ve düşünce üslubunun tanımı. LLM persona prompt'una aktarılır.",
                verbose_name="imza üslubu",
            ),
        ),
        migrations.AlterField(
            model_name="philosopher",
            name="slug",
            field=models.SlugField(
                help_text="URL dostu isim (ör: 'immanuel-kant'). Otomatik oluşturulabilir.",
                max_length=100,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="philosopher",
            name="system_prompt_template",
            field=models.TextField(
                help_text="LLM'e verilecek ana persona şablonu. {philosopher_name}, {era}, {core_concepts}, {signature_style}, {zeitgeist_block}, {rag_context}, {context_summary} yer tutucularını kullanabilirsiniz.",
                verbose_name="sistem prompt şablonu",
            ),
        ),
        migrations.AlterField(
            model_name="philosophicalwork",
            name="chunk_count",
            field=models.IntegerField(
                default=0,
                help_text="RAG için oluşturulan metin parçası sayısı.",
                verbose_name="chunk sayısı",
            ),
        ),
        migrations.AlterField(
            model_name="philosophicalwork",
            name="ingestion_error",
            field=models.TextField(
                blank=True,
                help_text="İşleme başarısız olduğunda hata detayı buraya kaydedilir.",
                verbose_name="hata mesajı",
            ),
        ),
        migrations.AlterField(
            model_name="philosophicalwork",
            name="original_file",
            field=models.FileField(
                blank=True,
                help_text="Yüklenecek PDF veya TXT dosyası. Doküman Bölüm 7.4: Yalnızca .pdf ve .txt, max 50MB.",
                null=True,
                upload_to="philosophical_works/",
                verbose_name="kaynak dosya",
            ),
        ),
        migrations.AlterField(
            model_name="philosophicalwork",
            name="title",
            field=models.CharField(
                help_text="Eserin tam başlığı.",
                max_length=200,
                verbose_name="eser başlığı",
            ),
        ),
        migrations.CreateModel(
            name="PhilosopherMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode_key",
                    models.CharField(
                        help_text="URL ve kod içinde kullanılan benzersiz anahtar. ör: 'socratic', 'dialectic', 'radical_doubt'",
                        max_length=50,
                        verbose_name="mod anahtarı",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="ör: 'Sokratik Sorgulama Modu'",
                        max_length=100,
                        verbose_name="görünen ad",
                    ),
                ),
                (
                    "button_label",
                    models.CharField(
                        help_text="ör: '🔍 Sokratik Mod'",
                        max_length=80,
                        verbose_name="buton etiketi",
                    ),
                ),
                (
                    "button_description",
                    models.CharField(
                        blank=True,
                        help_text="ör: 'Sorgulanarak öğren'",
                        max_length=150,
                        verbose_name="buton açıklaması",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="Bu mod için tam sistem promptu. Kullanılabilir yer tutucular: {zeitgeist_block}, {rag_context}, {context_summary}",
                        verbose_name="sistem promptu",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Bu filozofun profil sayfasında ilk/öne çıkan buton olarak göster.",
                        verbose_name="varsayılan mod",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="aktif")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="sıralama"),
                ),
                (
                    "philosopher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_modes",
                        to="philosophers.philosopher",
                        verbose_name="filozof",
                    ),
                ),
            ],
            options={
                "verbose_name": "filozof modu",
                "verbose_name_plural": "filozof modları",
                "ordering": ["display_order"],
                "unique_together": {("philosopher", "mode_key")},
            },
        ),
    ]
